name: Stop EC2 Instances

on:
  schedule:
    - cron: "0 19 * * 1-5" # 8 PM CET (7 PM UTC) from Monday to Friday
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  refurnishing:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }} # Optional: set if you're working in a specific region

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run the Python script
        run: python stop.py -s refurnishing

      - name: Output success message
        run: echo "EC2 instances has been stoped."

  staging:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }} # Optional: set if you're working in a specific region

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run the Python script
        run: python stop.py -s staging

      - name: Output success message
        run: echo "EC2 instances has been stopped"
